### PR TITLE
Use zerolog + intercept SIGINT

### PR DESCRIPTION
**Pull request by VaiTon**

### CODE REVIEW

**Comment by yunzheng** [comment]
Hi @VaiTon,

Thanks for the nice additions! Is it possible to change the timestamp format of zerolog to ISO format? now it logs only time and in am/pm notation.

**Comment by VaiTon** [comment]
@yunzheng done! :)

**Comment by yunzheng** [comment]
Thanks, looks much better :)

Can you also update the README.md with the new --help output as `-json` was added.

Also found a small issue, if the command failed to run (eg permission not denied) I cannot CTRL+C it. 

```shell
$ ./pcap-broker -cmd 'tcpdump -i eth0 -n --immediate-mode -s 65535 -U -w -'
2023-12-11T14:33:41Z ??? tcpdump: eth0: You don't have permission to capture on that device
(socket: Operation not permitted)
^C
<-- hangs here -->
```

Before it would just exit by default:

```shell
$ ./pcap-broker-orig -cmd 'tcpdump -i eth0 -n --immediate-mode -s 65535 -U -w -'
2023/12/11 14:34:23 config PCAP_COMMAND = "tcpdump -i eth0 -n --immediate-mode -s 65535 -U -w -"
2023/12/11 14:34:23 config LISTEN_ADDRESS = "localhost:4242"
2023/12/11 14:34:23 cmd = [tcpdump -i eth0 -n --immediate-mode -s 65535 -U -w -]
2023/12/11 14:34:23 PID 8837
tcpdump: eth0: You don't have permission to capture on that device
(socket: Operation not permitted)
2023/12/11 14:34:23 Process exited with error: exit status 1
```

**Comment by VaiTon** [comment]
@yunzheng all done (AFAIK :) )

**Review by yunzheng — APPROVED** [review]
Looks good to me, thanks for the contribution!

**Pull request merged**
